# Generated by Django 5.1.6 on 2025-02-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_follow_unique_together_remove_follow_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
