# Generated by Django 5.1.6 on 2025-03-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
