# Generated by Django 5.1.6 on 2025-03-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
